#!/usr/bin/env python3

import os


def main():
    if os.name == "nt":
        os.system("pip install -e . && cls && python app/index.py")
    else:
        os.system("pip install -e . && clear && python3 app/index.py")

if __name__ == "__main__":
    main()
